### ISSUE TITLE
Potential off by one error in getStartEndTickArrays() function in MIDIMethods class

### ISSUE THREAD

**Issue by dinamix1** [DDMAL/UtilityClasses#7]
It seems as though there is an inconsistency between normal sequence windowing and overlap offset windowing. In particular, an example can be found in the MIDIMethodsTest class starting at line 229 for the window overlap offset test. The second to last window seems to end 1 tick shorter than the other windows. This may be due to line 394 in MIDIMethods or line 414 in MIDIMethods. Also, this may be due to intentional logic that I am unaware of but regardless would be good to review for consistency.

**Comment by codaich** [comment]
Go through all the windowing-related code in UtilityClasses AND jSymbolic2 and check for windowing-related conceptual errors (in general, not just relating to the off-by-one-offset). Be particularly careful of int rounding, such as that discovered during our code review.  This isn't a big problem in and of itself, but I want to be sure that it isn't a sign of some bigger underlying problem.
